=== mmbase/mmbase/core/src/main/java/org/mmbase/util/xml/resources/builder.xsd
<?xml version="1.0"?>
<xsd:schema
    xmlns="http://www.mmbase.org/xmlns/builder"
    xmlns:dt="http://www.mmbase.org/xmlns/datatypes"
    targetNamespace="http://www.mmbase.org/xmlns/builder"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified"
    attributeFormDefault="unqualified"
    version="1.0"
    >

  <xsd:import
      namespace="http://www.w3.org/XML/1998/namespace"
      schemaLocation="https://www.w3.org/2001/03/xml.xsd"
      />

  <xsd:import
      namespace="http://www.mmbase.org/xmlns/datatypes"
      schemaLocation="https://www.mmbase.org/xmlns/datatypes.xsd"
      />

  <xsd:element name="builder">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="status" minOccurs="0" />
        <xsd:element ref="class" minOccurs="0" />
        <xsd:element ref="searchage" minOccurs="0" />
        <xsd:element ref="names" minOccurs="0" />
        <xsd:element ref="descriptions" minOccurs="0" />
        <xsd:element ref="properties" minOccurs="0" />
        <xsd:element ref="dt:datatypes"  minOccurs="0" />
        <xsd:element ref="fieldlist" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="indexlist" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="functionlist" minOccurs="0" maxOccurs="unbounded"  />
      </xsd:sequence>
      <xsd:attribute name="name"       type="xsd:string" use="required" />
      <xsd:attribute name="maintainer" type="xsd:string" />
      <xsd:attribute name="version"    type="xsd:string" />
      <xsd:attribute name="extends"    type="xsd:string" />
      <xsd:attribute name="defaultcontextintypedef"    type="xsd:string" />
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="status" />
  <xsd:element name="class">
    <xsd:complexType mixed="true">
      <xsd:sequence>
        <xsd:element ref="param" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute name="name" type="xsd:string" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="param">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute name="name" type="xsd:string" use="required" />
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="searchage" />

  <xsd:element name="names">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="singular" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="plural"   minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="singular">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute ref="xml:lang" />
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="plural">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute ref="xml:lang" />
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="descriptions">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="description" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="description">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute ref="xml:lang" />
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="properties">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="property" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="property">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute name="name" type="xsd:string" use="required" />
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>


  <xsd:element name="fieldlist">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="field" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
      <!-- you may want to xinclude fieldlists, xincludes may add xml:base attributes -->
      <xsd:attribute ref="xml:base" />
      <xsd:attribute name="id" type="xsd:ID"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="field">
    <xsd:complexType>
      <xsd:all>
        <xsd:element ref="descriptions" minOccurs="0" />
        <xsd:element ref="gui"          minOccurs="0" />
        <xsd:element ref="editor"       minOccurs="0" />
        <xsd:element ref="dt:datatype"     minOccurs="0" />
        <xsd:element ref="db"     minOccurs="0" />
      </xsd:all>
      <xsd:attribute name="name" type="xsd:string" />
      <xsd:attribute name="state">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="persistent" />
            <xsd:enumeration value="virtual" />
            <xsd:enumeration value="system" />
            <xsd:enumeration value="systemvirtual" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
      <xsd:attribute name="override">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="replace" />
            <xsd:enumeration value="merge" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
      <xsd:attribute name="readonly">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="true" />
            <xsd:enumeration value="false" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
      <!-- you may want to xinclude a field, xincludes may add xml:base attributes -->
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="gui">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="guiname" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="guiname">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute ref="xml:lang" />
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="editor">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="positions" minOccurs="0" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="positions">
    <xsd:complexType>
      <xsd:all>
        <xsd:element ref="input"  minOccurs="0" />
        <xsd:element ref="list"   minOccurs="0" />
        <xsd:element ref="search" minOccurs="0" />
      </xsd:all>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="input" />
  <xsd:element name="list" />
  <xsd:element name="search" />


  <xsd:element name="db">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="name" minOccurs="0" />
        <xsd:element ref="type" minOccurs="0" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="name" />

  <xsd:element name="type">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute name="state">
            <xsd:simpleType>
              <xsd:restriction base="xsd:string">
                <xsd:enumeration value="persistent" />
                <xsd:enumeration value="virtual" />
                <xsd:enumeration value="system" />
                <xsd:enumeration value="systemvirtual" />
              </xsd:restriction>
            </xsd:simpleType>
          </xsd:attribute>
          <xsd:attribute name="size" type="xsd:string" />
          <xsd:attribute name="notnull">
            <xsd:simpleType>
              <xsd:restriction base="xsd:string">
                <xsd:enumeration value="true" />
                <xsd:enumeration value="false" />
              </xsd:restriction>
            </xsd:simpleType>
          </xsd:attribute>
          <xsd:attribute name="unique">
            <xsd:simpleType>
              <xsd:restriction base="xsd:string">
                <xsd:enumeration value="true" />
                <xsd:enumeration value="false" />
                <xsd:enumeration value="implied" />
              </xsd:restriction>
            </xsd:simpleType>
          </xsd:attribute>
          <xsd:attribute name="required">
            <xsd:simpleType>
              <xsd:restriction base="xsd:string">
                <xsd:enumeration value="true" />
                <xsd:enumeration value="false" />
              </xsd:restriction>
            </xsd:simpleType>
          </xsd:attribute>
          <xsd:attribute name="readonly">
            <xsd:simpleType>
              <xsd:restriction base="xsd:string">
                <xsd:enumeration value="true" />
                <xsd:enumeration value="false" />
              </xsd:restriction>
            </xsd:simpleType>
          </xsd:attribute>
          <xsd:attribute name="key">
            <xsd:simpleType>
              <xsd:restriction base="xsd:string">
                <xsd:enumeration value="true" />
                <xsd:enumeration value="false" />
              </xsd:restriction>
            </xsd:simpleType>
          </xsd:attribute>
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="indexlist">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="index" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="index">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="indexfield" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute name="name" type="xsd:string" use="required" />
      <xsd:attribute name="override">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="replace" />
            <xsd:enumeration value="merge" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
      <xsd:attribute name="unique">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="true" />
            <xsd:enumeration value="false" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="indexfield">
    <xsd:complexType>
      <xsd:attribute name="name" type="xsd:string" use="required" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="functionlist">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="function" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="function">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="class" />
      </xsd:sequence>
      <xsd:attribute ref="xml:base" />
      <xsd:attribute name="name" type="xsd:string" />
      <xsd:attribute name="key" type="xsd:string" />
      <xsd:attribute name="override">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="replace" />
            <xsd:enumeration value="merge" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== mmbase/mmbase/contributions/CMSContainer_Modules/rating/config/applications/rating/builders/rating.xml
<?xml version="1.0" encoding="UTF-8"?>
<builder xmlns="http://www.mmbase.org/xmlns/builder"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.mmbase.org/xmlns/builder 
                        http://www.mmbase.org/xmlns/builder.xsd"
	extends="object" maintainer="finalist.com" name="rating" version="1">
	<!--
		
	-->
	<status>active</status>
	<!--
		<class>Tasks.Task</class>
	-->
	<searchage>70</searchage>
	<names>
		<singular xml:lang="nl">rating</singular>
		<singular xml:lang="en">rating</singular>
		<plural xml:lang="nl">ratings</plural>
		<plural xml:lang="en">ratings</plural>
	</names>
	<descriptions>
		<description xml:lang="nl"></description>
		<description xml:lang="en"></description>
	</descriptions>
	<properties></properties>
	<fieldlist>
		<field>
			<descriptions>
				<description xml:lang="nl"></description>
				<description xml:lang="en"></description>
			</descriptions>
			<gui>
				<guiname xml:lang="nl">Gebruiker</guiname>
				<guiname xml:lang="en">User</guiname>
			</gui>
			<editor>
				<positions>
					<input>1</input>
					<list>-1</list>
					<search>-1</search>
				</positions>
			</editor>
			<datatype base="line" xmlns="http://www.mmbase.org/xmlns/datatypes" />
			<db>
				<name>user</name>
            <type key="false" notnull="false" state="persistent">INTEGER</type>
			</db>
		</field>
		<field>
			<descriptions>
				<description xml:lang="nl"></description>
				<description xml:lang="en"></description>
			</descriptions>
			<gui>
				<guiname xml:lang="nl">Timestamp</guiname>
				<guiname xml:lang="en">timestamp</guiname>
			</gui>
			<editor>
				<positions>
					<input>2</input>
					<list>-1</list>
					<search>-1</search>
				</positions>
			</editor>
			<datatype base="created" xmlns="http://www.mmbase.org/xmlns/datatypes" />
			<db>
				<name>timestamp</name>
				<type key="false" notnull="false" state="system">DATETIME</type>
			</db>
		</field>
		<field>
			<descriptions>
				<description xml:lang="nl"></description>
				<description xml:lang="en"></description>
			</descriptions>
			<gui>
				<guiname xml:lang="nl">Rating</guiname>
				<guiname xml:lang="en">Rating</guiname>
			</gui>
			<editor>
				<positions>
					<input>3</input>
					<list>-1</list>
					<search>-1</search>
				</positions>
			</editor>
			<db>
				<name>rating</name>
            <type key="false" notnull="false" state="persistent">INTEGER</type>
			</db>
		</field>
	</fieldlist>
</builder>

=== mmbase/mmbase/contributions/didactor2/src/education/config/builders/didactor_education/pages.xml
<?xml version="1.0" encoding="UTF-8"?>
<builder
    xmlns="http://www.mmbase.org/xmlns/builder"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.mmbase.org/xmlns/builder http://www.mmbase.org/xmlns/builder.xsd"
    name="pages" maintainer="didactor.nl" version="3" extends="learnobjects">
  <class>nl.didactor.builders.DidactorBuilder</class>
  <searchage>31</searchage>
  <names>
    <singular xml:lang="nl">Pagina</singular>
    <singular xml:lang="en">Page</singular>
    <singular xml:lang="fr">Page</singular>
    <plural xml:lang="nl">Pagina's</plural>
    <plural xml:lang="en">Pages</plural>
    <plural xml:lang="fr">Pages</plural>
  </names>

  <descriptions>
    <description xml:lang="nl">Een pagina met cursus-stof</description>
    <description xml:lang="en">A page with course material</description>
  </descriptions>

  <fieldlist>
    <field name="text">
      <descriptions>
        <description xml:lang="nl">Tekst, met eventueel HTML opmaak</description>
        <description xml:lang="en">Text, possibly containt HTML layout</description>
      </descriptions>
      <gui>
        <guiname xml:lang="nl">Tekst</guiname>
        <guiname xml:lang="en">Text</guiname>
      </gui>
      <editor>
        <positions>
          <list>1</list>
        </positions>
      </editor>
      <datatype base="field" xmlns="http://www.mmbase.org/xmlns/datatypes" >
        <maxLength value="65535" enforce="never"/>
      </datatype>
    </field>

    <field name="layout">
      <descriptions>
        <description xml:lang="nl">Layout</description>
        <description xml:lang="en">Layout</description>
      </descriptions>
      <gui>
        <guiname xml:lang="nl">Layout</guiname>
        <guiname xml:lang="en">Layout</guiname>
      </gui>
      <datatype base="didactor_layout" xmlns="http://www.mmbase.org/xmlns/datatypes" />
    </field>

    <field>
      <descriptions>
        <!-- descriptions per language as defined by ISO 639  -->
        <description xml:lang="nl">Layout afbeeldingen</description>
        <description xml:lang="en">Images layout</description>
      </descriptions>
      <!-- gui related -->
      <gui>
        <guiname xml:lang="nl">Layout afbeeldingen</guiname>
        <guiname xml:lang="en">Images layout</guiname>
        <guitype>integer</guitype>
      </gui>
      <!-- editor related  -->
      <editor>
        <positions>
          <!-- position in the input area of the editor -->
          <input>2</input>
          <!-- position in list area of the editor -->
          <list>2</list>
          <!-- position in search area of the editor -->
          <search>2</search>
        </positions>
      </editor>
      <!-- database related  -->
      <db>
        <!-- name of the field in the database -->
        <name>imagelayout</name>
        <!-- MMBase datatype and demands on it -->
        <type state="persistent" notnull="true">INTEGER</type>
      </db>
    </field>

  </fieldlist>
</builder>

=== mmbase/mmbase/mmbase/tags/v1_4_12/contributions/CMSContainer/cmsc/contentrepository/config/applications/contentrepository/builders/contentrel.xml
<?xml version="1.0" encoding="UTF-8"?>
<builder
    xmlns="http://www.mmbase.org/xmlns/builder"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.mmbase.org/xmlns/builder 
                        http://www.mmbase.org/xmlns/builder.xsd"
	extends="insrel" maintainer="finalist.com" name="contentrel" version="1">
<!--
 
-->
   <status>active</status>
   <!--
   <class>ContentRepository.Contentrel</class>
   -->
   <searchage>70</searchage>
   <names>
      <singular xml:lang="nl">contentrel</singular>
      <singular xml:lang="en">contentrel</singular>
	  <singular xml:lang="zh">内容连接</singular>
      <plural xml:lang="nl">contentrel</plural>
      <plural xml:lang="en">contentrel</plural>
	  <plural xml:lang="zh">内容连接</plural>
   </names>
   <descriptions>
      <description xml:lang="nl"></description>
      <description xml:lang="en"></description>
	  <description xml:lang="zh"></description>
   </descriptions>
	<properties>
		</properties>
   <fieldlist>
      <field>
         <descriptions>
            <description xml:lang="nl"></description>
            <description xml:lang="en"></description>
			<description xml:lang="zh"></description>
         </descriptions>
         <gui>
            <guiname xml:lang="nl">Positie</guiname>
            <guiname xml:lang="en">pos</guiname>
			<guiname xml:lang="zh">位置</guiname>
         </gui>
         <editor>
            <positions>
                                           <input>4</input>
               <list>-1</list>
               <search>-1</search>
            </positions>
         </editor>
         <db>
            <name>pos</name>
            <type key="false" notnull="false" state="persistent">INTEGER</type>
         </db>
      </field>
</fieldlist>
</builder>

=== mmbase/mmbase/config/builders/core/systemproperties.xml
<?xml version="1.0" encoding="UTF-8"?>
<builder xmlns="http://www.mmbase.org/xmlns/builder" 
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xsi:schemaLocation="http://www.mmbase.org/xmlns/builder http://www.mmbase.org/xmlns/builder.xsd" 
   name="systemproperties" maintainer="mmbase.org" version="1" extends="object">

   <searchage>1000</searchage>
   <names>
      <singular xml:lang="nl">Systeem instelling</singular>
      <singular xml:lang="en">System properties</singular>
    <singular xml:lang="zh">属性</singular>
      <plural xml:lang="nl">System instellingen</plural>
      <plural xml:lang="en">System properties</plural>
    <plural xml:lang="zh">属性</plural>
   </names>
   <descriptions>
      <description xml:lang="nl"/>
      <description xml:lang="en"/>
    <description xml:lang="zh"/>
   </descriptions>

   <fieldlist>
      <field name="key" state="persistent">
         <descriptions>
            <description xml:lang="nl"/>
            <description xml:lang="en"/>
            <description xml:lang="zh"/>
         </descriptions>
         <gui>
            <guiname xml:lang="nl">Naam</guiname>
            <guiname xml:lang="en">Key</guiname>
            <guiname xml:lang="zh">关键字</guiname>
         </gui>
         <editor>
            <positions>
               <input>4</input>
               <list>4</list>
               <search>4</search>
            </positions>
         </editor>
         <datatype xmlns="http://www.mmbase.org/xmlns/datatypes" base="line">
            <unique value="true"/>
            <required value="true"/>
            <maxLength value="128"/>
         </datatype>
      </field>
      <field name="description" state="persistent">
         <descriptions>
            <description xml:lang="nl"/>
            <description xml:lang="en"/>
            <description xml:lang="zh"/>
         </descriptions>
         <gui>
            <guiname xml:lang="nl">Omschrijving</guiname>
            <guiname xml:lang="en">Description</guiname>
            <guiname xml:lang="zh">描述</guiname>
         </gui>
         <editor>
            <positions>
               <input>5</input>
            </positions>
         </editor>
         <datatype xmlns="http://www.mmbase.org/xmlns/datatypes" base="field">
            <maxLength value="1024"/>
         </datatype>
      </field>
      <field name="value" state="persistent">
         <descriptions>
            <description xml:lang="nl"/>
            <description xml:lang="en"/>
            <description xml:lang="zh"/>
         </descriptions>
         <gui>
            <guiname xml:lang="nl">Waarde</guiname>
            <guiname xml:lang="en">Value</guiname>
            <guiname xml:lang="zh">值</guiname>
         </gui>
         <editor>
            <positions>
               <input>6</input>
               <list>-1</list>
               <search>-1</search>
            </positions>
         </editor>
         <datatype base="field" xmlns="http://www.mmbase.org/xmlns/datatypes">
            <required value="true"/>
            <maxLength value="1024"/>
         </datatype>
      </field>
      <field name="production" state="persistent">
         <descriptions>
            <description xml:lang="nl"/>
            <description xml:lang="en"/>
            <description xml:lang="zh"/>
         </descriptions>
         <gui>
            <guiname xml:lang="nl">Productie</guiname>
            <guiname xml:lang="en">Production</guiname>
            <guiname xml:lang="zh">生产</guiname>
         </gui>
         <editor>
            <positions>
               <input>7</input>
               <list>-1</list>
               <search>-1</search>
            </positions>
         </editor>
         <datatype base="field" xmlns="http://www.mmbase.org/xmlns/datatypes">
            <required value="true"/>
            <maxLength value="1024"/>
         </datatype>
      </field>
      <field name="acceptance" state="persistent">
         <descriptions>
            <description xml:lang="nl"/>
            <description xml:lang="en"/>
            <description xml:lang="zh"/>
         </descriptions>
         <gui>
            <guiname xml:lang="nl">Acceptatie</guiname>
            <guiname xml:lang="en">Acceptance</guiname>
            <guiname xml:lang="zh">认可</guiname>
         </gui>
         <editor>
            <positions>
               <input>8</input>
               <list>-1</list>
               <search>-1</search>
            </positions>
         </editor>
         <datatype base="field" xmlns="http://www.mmbase.org/xmlns/datatypes">
            <required value="true"/>
            <maxLength value="1024"/>
         </datatype>
      </field>
      <field name="test" state="persistent">
         <descriptions>
            <description xml:lang="nl"/>
            <description xml:lang="en"/>
            <description xml:lang="zh"/>
         </descriptions>
         <gui>
            <guiname xml:lang="nl">Test</guiname>
            <guiname xml:lang="en">Test</guiname>
            <guiname xml:lang="zh">测试</guiname>
         </gui>
         <editor>
            <positions>
               <input>9</input>
               <list>-1</list>
               <search>-1</search>
            </positions>
         </editor>
         <datatype base="field" xmlns="http://www.mmbase.org/xmlns/datatypes">
            <required value="true"/>
            <maxLength value="1024"/>
         </datatype>
      </field>
      <field name="development" state="persistent">
         <descriptions>
            <description xml:lang="nl"/>
            <description xml:lang="en"/>
            <description xml:lang="zh"/>
         </descriptions>
         <gui>
            <guiname xml:lang="nl">Development</guiname>
            <guiname xml:lang="en">Development</guiname>
            <guiname xml:lang="zh">开发</guiname>
         </gui>
         <editor>
            <positions>
               <input>10</input>
               <list>-1</list>
               <search>-1</search>
            </positions>
         </editor>
         <datatype base="field" xmlns="http://www.mmbase.org/xmlns/datatypes">
            <required value="true"/>
            <maxLength value="1024"/>
         </datatype>
      </field>
      <field name="component" state="persistent">
         <descriptions>
            <description xml:lang="nl"/>
            <description xml:lang="en"/>
            <description xml:lang="zh"/>
         </descriptions>
         <gui>
            <guiname xml:lang="nl">Component</guiname>
            <guiname xml:lang="en">Component</guiname>
            <guiname xml:lang="zh">模型</guiname>
         </gui>
         <editor>
            <positions>
               <input>10</input>
               <list>-1</list>
               <search>-1</search>
            </positions>
         </editor>
         <datatype base="field" xmlns="http://www.mmbase.org/xmlns/datatypes">
            <required value="true"/>
            <maxLength value="1024"/>
         </datatype>
      </field>
   </fieldlist>
</builder>

=== mmbase/mmbase/contributions/CMSContainer_Modules/workflow/config/builders/workflow/workflowrel.xml
<?xml version="1.0" encoding="UTF-8"?>
<builder extends="insrel" maintainer="finalist.com" name="workflowrel"
    version="1" xmlns="http://www.mmbase.org/xmlns/builder"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mmbase.org/xmlns/builder http://www.mmbase.org/xmlns/builder.xsd">
    <names>
        <singular xml:lang="nl">workflowrel</singular>
        <singular xml:lang="en">workflowrel</singular>
        <singular xml:lang="zh">工作流链接</singular>
        <plural xml:lang="nl">workflowrel</plural>
        <plural xml:lang="en">workflowrel</plural>
        <plural xml:lang="zh">工作流链接</plural>
    </names>
    <fieldlist/>
</builder>
