=== mmbase/mmbase/core/src/main/java/org/mmbase/util/xml/resources/builder.xsd
<?xml version="1.0"?>
<xsd:schema
    xmlns="http://www.mmbase.org/xmlns/builder"
    xmlns:dt="http://www.mmbase.org/xmlns/datatypes"
    targetNamespace="http://www.mmbase.org/xmlns/builder"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified"
    attributeFormDefault="unqualified"
    version="1.0"
    >

  <xsd:import
      namespace="http://www.w3.org/XML/1998/namespace"
      schemaLocation="https://www.w3.org/2001/03/xml.xsd"
      />

  <xsd:import
      namespace="http://www.mmbase.org/xmlns/datatypes"
      schemaLocation="https://www.mmbase.org/xmlns/datatypes.xsd"
      />

  <xsd:element name="builder">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="status" minOccurs="0" />
        <xsd:element ref="class" minOccurs="0" />
        <xsd:element ref="searchage" minOccurs="0" />
        <xsd:element ref="names" minOccurs="0" />
        <xsd:element ref="descriptions" minOccurs="0" />
        <xsd:element ref="properties" minOccurs="0" />
        <xsd:element ref="dt:datatypes"  minOccurs="0" />
        <xsd:element ref="fieldlist" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="indexlist" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="functionlist" minOccurs="0" maxOccurs="unbounded"  />
      </xsd:sequence>
      <xsd:attribute name="name"       type="xsd:string" use="required" />
      <xsd:attribute name="maintainer" type="xsd:string" />
      <xsd:attribute name="version"    type="xsd:string" />
      <xsd:attribute name="extends"    type="xsd:string" />
      <xsd:attribute name="defaultcontextintypedef"    type="xsd:string" />
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="status" />
  <xsd:element name="class">
    <xsd:complexType mixed="true">
      <xsd:sequence>
        <xsd:element ref="param" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute name="name" type="xsd:string" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="param">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute name="name" type="xsd:string" use="required" />
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="searchage" />

  <xsd:element name="names">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="singular" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="plural"   minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="singular">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute ref="xml:lang" />
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="plural">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute ref="xml:lang" />
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="descriptions">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="description" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="description">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute ref="xml:lang" />
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="properties">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="property" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="property">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute name="name" type="xsd:string" use="required" />
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>


  <xsd:element name="fieldlist">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="field" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
      <!-- you may want to xinclude fieldlists, xincludes may add xml:base attributes -->
      <xsd:attribute ref="xml:base" />
      <xsd:attribute name="id" type="xsd:ID"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="field">
    <xsd:complexType>
      <xsd:all>
        <xsd:element ref="descriptions" minOccurs="0" />
        <xsd:element ref="gui"          minOccurs="0" />
        <xsd:element ref="editor"       minOccurs="0" />
        <xsd:element ref="dt:datatype"     minOccurs="0" />
        <xsd:element ref="db"     minOccurs="0" />
      </xsd:all>
      <xsd:attribute name="name" type="xsd:string" />
      <xsd:attribute name="state">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="persistent" />
            <xsd:enumeration value="virtual" />
            <xsd:enumeration value="system" />
            <xsd:enumeration value="systemvirtual" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
      <xsd:attribute name="override">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="replace" />
            <xsd:enumeration value="merge" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
      <xsd:attribute name="readonly">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="true" />
            <xsd:enumeration value="false" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
      <!-- you may want to xinclude a field, xincludes may add xml:base attributes -->
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="gui">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="guiname" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="guiname">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute ref="xml:lang" />
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="editor">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="positions" minOccurs="0" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="positions">
    <xsd:complexType>
      <xsd:all>
        <xsd:element ref="input"  minOccurs="0" />
        <xsd:element ref="list"   minOccurs="0" />
        <xsd:element ref="search" minOccurs="0" />
      </xsd:all>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="input" />
  <xsd:element name="list" />
  <xsd:element name="search" />


  <xsd:element name="db">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="name" minOccurs="0" />
        <xsd:element ref="type" minOccurs="0" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="name" />

  <xsd:element name="type">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute name="state">
            <xsd:simpleType>
              <xsd:restriction base="xsd:string">
                <xsd:enumeration value="persistent" />
                <xsd:enumeration value="virtual" />
                <xsd:enumeration value="system" />
                <xsd:enumeration value="systemvirtual" />
              </xsd:restriction>
            </xsd:simpleType>
          </xsd:attribute>
          <xsd:attribute name="size" type="xsd:string" />
          <xsd:attribute name="notnull">
            <xsd:simpleType>
              <xsd:restriction base="xsd:string">
                <xsd:enumeration value="true" />
                <xsd:enumeration value="false" />
              </xsd:restriction>
            </xsd:simpleType>
          </xsd:attribute>
          <xsd:attribute name="unique">
            <xsd:simpleType>
              <xsd:restriction base="xsd:string">
                <xsd:enumeration value="true" />
                <xsd:enumeration value="false" />
                <xsd:enumeration value="implied" />
              </xsd:restriction>
            </xsd:simpleType>
          </xsd:attribute>
          <xsd:attribute name="required">
            <xsd:simpleType>
              <xsd:restriction base="xsd:string">
                <xsd:enumeration value="true" />
                <xsd:enumeration value="false" />
              </xsd:restriction>
            </xsd:simpleType>
          </xsd:attribute>
          <xsd:attribute name="readonly">
            <xsd:simpleType>
              <xsd:restriction base="xsd:string">
                <xsd:enumeration value="true" />
                <xsd:enumeration value="false" />
              </xsd:restriction>
            </xsd:simpleType>
          </xsd:attribute>
          <xsd:attribute name="key">
            <xsd:simpleType>
              <xsd:restriction base="xsd:string">
                <xsd:enumeration value="true" />
                <xsd:enumeration value="false" />
              </xsd:restriction>
            </xsd:simpleType>
          </xsd:attribute>
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="indexlist">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="index" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="index">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="indexfield" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute name="name" type="xsd:string" use="required" />
      <xsd:attribute name="override">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="replace" />
            <xsd:enumeration value="merge" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
      <xsd:attribute name="unique">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="true" />
            <xsd:enumeration value="false" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="indexfield">
    <xsd:complexType>
      <xsd:attribute name="name" type="xsd:string" use="required" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="functionlist">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="function" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="function">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="class" />
      </xsd:sequence>
      <xsd:attribute ref="xml:base" />
      <xsd:attribute name="name" type="xsd:string" />
      <xsd:attribute name="key" type="xsd:string" />
      <xsd:attribute name="override">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="replace" />
            <xsd:enumeration value="merge" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== mmbase/mmbase/mmbase/trunk/contributions/CMSContainer_Portlets/portlets-newsletter/config/applications/newsletter/builders/newsletterdailylog.xml
<?xml version="1.0" encoding="UTF-8"?>
<builder xmlns="http://www.mmbase.org/xmlns/builder"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.mmbase.org/xmlns/builder  http://www.mmbase.org/xmlns/builder.xsd"
         extends="object"
         maintainer="finalist.com"
         name="newsletterdailylog"
         version="1">

   <status>active</status>
   <searchage>70</searchage>
   <names>
      <singular xml:lang="nl">Dagelijkse log</singular>
      <singular xml:lang="en">Daily Log</singular>
      <plural xml:lang="nl">Dagelijkse Logs</plural>
      <plural xml:lang="en">Daily Logs</plural>
   </names>
   <descriptions>
      <description xml:lang="nl"></description>
      <description xml:lang="en"></description>
   </descriptions>
   <properties></properties>
   <fieldlist>
      <field>
         <descriptions>
            <description xml:lang="nl"></description>
            <description xml:lang="en"></description>
         </descriptions>
         <gui>
            <guiname xml:lang="nl">post</guiname>
            <guiname xml:lang="en">post</guiname>
         </gui>
         <editor>
            <positions>
               <input>1</input>
               <list>-1</list>
               <search>-1</search>
            </positions>
         </editor>
         <datatype base="line" xmlns="http://www.mmbase.org/xmlns/datatypes"></datatype>
         <db>
            <name>post</name>
            <type key="false" notnull="false" size="100" state="persistent">INTEGER</type>
         </db>
      </field>
      <field>
         <descriptions>
            <description xml:lang="nl"></description>
            <description xml:lang="en"></description>
         </descriptions>
         <gui>
            <guiname xml:lang="nl">bounches</guiname>
            <guiname xml:lang="en">bounches</guiname>
         </gui>
         <editor>
            <positions>
               <input>1</input>
               <list>-1</list>
               <search>-1</search>
            </positions>
         </editor>
         <datatype base="line" xmlns="http://www.mmbase.org/xmlns/datatypes"></datatype>
         <db>
            <name>bounches</name>
            <type key="false" notnull="false" size="100" state="persistent">INTEGER</type>
         </db>
      </field>
      <field>
         <descriptions>
            <description xml:lang="nl"></description>
            <description xml:lang="en"></description>
         </descriptions>
         <gui>
            <guiname xml:lang="nl">subscribe</guiname>
            <guiname xml:lang="en">subscribe</guiname>
         </gui>
         <editor>
            <positions>
               <input>1</input>
               <list>-1</list>
               <search>-1</search>
            </positions>
         </editor>
         <datatype base="line" xmlns="http://www.mmbase.org/xmlns/datatypes"></datatype>
         <db>
            <name>subscribe</name>
            <type key="false" notnull="false" size="100" state="persistent">INTEGER</type>
         </db>
      </field>
      <field>
         <descriptions>
            <description xml:lang="nl"></description>
            <description xml:lang="en"></description>
         </descriptions>
         <gui>
            <guiname xml:lang="nl">unsubscribe</guiname>
            <guiname xml:lang="en">unsubscribe</guiname>
         </gui>
         <editor>
            <positions>
               <input>1</input>
               <list>-1</list>
               <search>-1</search>
            </positions>
         </editor>
         <datatype base="line" xmlns="http://www.mmbase.org/xmlns/datatypes"></datatype>
         <db>
            <name>unsubscribe</name>
            <type key="false" notnull="false" size="100" state="persistent">INTEGER</type>
         </db>
      </field>
      <field>
         <descriptions>
            <description xml:lang="nl"></description>
            <description xml:lang="en"></description>
         </descriptions>
         <gui>
            <guiname xml:lang="nl">verwijderd</guiname>
            <guiname xml:lang="en">removed</guiname>
         </gui>
         <editor>
            <positions>
               <input>1</input>
               <list>-1</list>
               <search>-1</search>
            </positions>
         </editor>
         <datatype base="line" xmlns="http://www.mmbase.org/xmlns/datatypes"></datatype>
         <db>
            <name>removed</name>
            <type key="false" notnull="false" size="100" state="persistent">INTEGER</type>
         </db>
      </field>
      <field>
         <descriptions>
            <description xml:lang="nl"></description>
            <description xml:lang="en"></description>
         </descriptions>
         <gui>
            <guiname xml:lang="nl">logdatum</guiname>
            <guiname xml:lang="en">log date</guiname>
         </gui>
         <editor>
            <positions>
               <input>1</input>
               <list>-1</list>
               <search>-1</search>
            </positions>
         </editor>
         <datatype  xmlns="http://www.mmbase.org/xmlns/datatypes"></datatype>
         <db>
            <name>logdate</name>
           	<type key="false" required="false" state="persistent">DATETIME</type>
         </db>
      </field>
      <field>
         <descriptions>
            <description xml:lang="nl"></description>
            <description xml:lang="en"></description>
         </descriptions>
         <gui>
            <guiname xml:lang="nl">nieuwsbrief</guiname>
            <guiname xml:lang="en">newsletter</guiname>
         </gui>
         <editor>
            <positions>
               <input>1</input>
               <list>-1</list>
               <search>-1</search>
            </positions>
         </editor>
         <datatype base="line" xmlns="http://www.mmbase.org/xmlns/datatypes"></datatype>
         <db>
            <name>newsletter</name>
            <type key="false" notnull="false" size="100" state="persistent">INTEGER</type>
         </db>
      </field>
      <field>
         <descriptions>
            <description xml:lang="nl"></description>
            <description xml:lang="en"></description>
         </descriptions>
         <gui>
            <guiname xml:lang="nl">Gebruikers-ID</guiname>
            <guiname xml:lang="en">UserId</guiname>
         </gui>
         <editor>
            <positions>
               <input>1</input>
               <list>-1</list>
               <search>-1</search>
            </positions>
         </editor>
         <datatype base="line" xmlns="http://www.mmbase.org/xmlns/datatypes"></datatype>
         <db>
            <name>userid</name>
            <type key="false" notnull="false" size="100" state="persistent">INTEGER</type>
         </db>
      </field>
   </fieldlist>
</builder>

=== mmbase/mmbase/mmbase/trunk/contributions/CMSContainer_Portlets/portlets-guestbook/config/applications/guestbook/builders/guestmessage.xml
<?xml version="1.0" encoding="UTF-8"?>
<builder xmlns="http://www.mmbase.org/xmlns/builder"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.mmbase.org/xmlns/builder 
                        http://www.mmbase.org/xmlns/builder.xsd"
	extends="object" maintainer="finalist.com" name="guestmessage" version="1">

	<status>active</status>
<!-- <class>com.finalist.cmsc.richtext.builders.RichTextBuilder</class>  -->
	<searchage>70</searchage>
	<names>
		<singular xml:lang="nl">Bericht</singular>
		<singular xml:lang="en">Message</singular>
		<singular xml:lang="zh">信息</singular>
		<plural xml:lang="nl">Berichten</plural>
		<plural xml:lang="en">Messages</plural>
		<plural xml:lang="zh">信息</plural>
	</names>
	<descriptions>
		<description xml:lang="nl"></description>
		<description xml:lang="en"></description>
		<description xml:lang="zh"></description>
	</descriptions>
	<properties>
	</properties>
	<fieldlist>
		<field>
			<descriptions>
				<description xml:lang="nl"></description>
				<description xml:lang="en"></description>
				<description xml:lang="zh"></description>
			</descriptions>
			<gui>
				<guiname xml:lang="nl">Titel</guiname>
				<guiname xml:lang="en">Title</guiname>
				<guiname xml:lang="zh">标题</guiname>
			</gui>
			<editor>
				<positions>
					<input>10</input>
					<list>10</list>
					<search>10</search>
				</positions>
			</editor>
			<datatype base="line" xmlns="http://www.mmbase.org/xmlns/datatypes" />
			<db>
				<name>title</name>
				<type key="false" notnull="true" size="512" state="persistent">STRING</type>
			</db>
		</field>
		<field>
			<descriptions>
				<description xml:lang="nl"></description>
				<description xml:lang="en"></description>
				<description xml:lang="zh"></description>
			</descriptions>
			<gui>
				<guiname xml:lang="nl">Naam</guiname>
				<guiname xml:lang="en">Name</guiname>
				<guiname xml:lang="zh">名称</guiname>
			</gui>
			<editor>
				<positions>
					<input>10</input>
					<list>10</list>
					<search>10</search>
				</positions>
			</editor>
			<datatype base="line" xmlns="http://www.mmbase.org/xmlns/datatypes" />
			<db>
				<name>name</name>
				<type key="false" notnull="true" size="512" state="persistent">STRING</type>
			</db>
		</field>
        <field>
            <descriptions>
                <description xml:lang="nl"></description>
                <description xml:lang="en"></description>
				<description xml:lang="zh"></description>
            </descriptions>
            <gui>
                <guiname xml:lang="nl">Email</guiname>
                <guiname xml:lang="en">Email</guiname>
				<guiname xml:lang="zh">邮件</guiname>
            </gui>
            <editor>
                <positions>
                    <input>10</input>
                    <list>10</list>
                    <search>10</search>
                </positions>
            </editor>
            <datatype base="line" xmlns="http://www.mmbase.org/xmlns/datatypes" />
            <db>
                <name>email</name>
                <type key="false" notnull="false" size="255" state="persistent">STRING</type>
            </db>
        </field>
		<field>
			<descriptions>
				<description xml:lang="nl"></description>
				<description xml:lang="en"></description>
				<description xml:lang="zh"></description>
			</descriptions>
			<gui>
				<guiname xml:lang="nl">Aangemaakt</guiname>
				<guiname xml:lang="en">Creationdate</guiname>
				<guiname xml:lang="zh">创建时间</guiname>
			</gui>
			<editor>
				<positions>
					<input>4</input>
					<list>-1</list>
					<search>-1</search>
				</positions>
			</editor>
			<datatype base="created" xmlns="http://www.mmbase.org/xmlns/datatypes" />
			<db>
				<name>creationdate</name>
				<type key="false" notnull="false" state="system">DATETIME</type>
			</db>
		</field>
		<field>
			<descriptions>
				<description xml:lang="nl"></description>
				<description xml:lang="en"></description>
				<description xml:lang="zh"></description>
			</descriptions>
			<gui>
				<guiname xml:lang="nl">Tekst</guiname>
				<guiname xml:lang="en">Body</guiname>
				<guiname xml:lang="zh">主体</guiname>
			</gui>
			<editor>
				<positions>
					<input>6</input>
					<list>-1</list>
					<search>-1</search>
				</positions>
			</editor>
			<datatype base="cmscrichtext" xmlns="http://www.mmbase.org/xmlns/datatypes" />
			<db>
				<name>body</name>
				<type key="false" notnull="false" size="512000" state="persistent">STRING</type>
			</db>
		</field>
	</fieldlist>
</builder>

=== mmbase/mmbase/contributions/CMSContainer_Portlets/portlets-dynamicforms/config/builders/responseform/savedfieldvalue.xml
<?xml version="1.0" encoding="UTF-8"?>
<builder extends="object" maintainer="mmbase.org" name="savedfieldvalue"
    version="1" xmlns="http://www.mmbase.org/xmlns/builder"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mmbase.org/xmlns/builder http://www.mmbase.org/xmlns/builder.xsd">
    <names>
        <singular xml:lang="nl">Opgeslagen veldwaarde</singular>
        <singular xml:lang="en">Saved field value</singular>
        <singular xml:lang="zh">保存框值</singular>
        <plural xml:lang="nl">Opgeslagen veldwaarden</plural>
        <plural xml:lang="en">Saved field value</plural>
        <plural xml:lang="zh">保存框值</plural>
    </names>
    <fieldlist>
        <field name="field">
            <gui>
                <guiname xml:lang="nl">Veld</guiname>
                <guiname xml:lang="en">Field</guiname>
                <guiname xml:lang="zh">框</guiname>
            </gui>
            <editor>
                <positions>
                    <input>4</input>
                </positions>
            </editor>
            <datatype base="line" xmlns="http://www.mmbase.org/xmlns/datatypes">
                <maxLength value="255"/>
            </datatype>
        </field>
        <field name="value">
            <gui>
                <guiname xml:lang="nl">Waarde</guiname>
                <guiname xml:lang="en">Value</guiname>
                <guiname xml:lang="zh">值</guiname>
            </gui>
            <editor>
                <positions>
                    <input>5</input>
                </positions>
            </editor>
            <datatype base="line" xmlns="http://www.mmbase.org/xmlns/datatypes">
                <maxLength value="64000"/>
            </datatype>
        </field>
    </fieldlist>
</builder>
