=== mmbase/mmbase/core/src/main/java/org/mmbase/util/xml/resources/builder.xsd
<?xml version="1.0"?>
<xsd:schema
    xmlns="http://www.mmbase.org/xmlns/builder"
    xmlns:dt="http://www.mmbase.org/xmlns/datatypes"
    targetNamespace="http://www.mmbase.org/xmlns/builder"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified"
    attributeFormDefault="unqualified"
    version="1.0"
    >

  <xsd:import
      namespace="http://www.w3.org/XML/1998/namespace"
      schemaLocation="https://www.w3.org/2001/03/xml.xsd"
      />

  <xsd:import
      namespace="http://www.mmbase.org/xmlns/datatypes"
      schemaLocation="https://www.mmbase.org/xmlns/datatypes.xsd"
      />

  <xsd:element name="builder">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="status" minOccurs="0" />
        <xsd:element ref="class" minOccurs="0" />
        <xsd:element ref="searchage" minOccurs="0" />
        <xsd:element ref="names" minOccurs="0" />
        <xsd:element ref="descriptions" minOccurs="0" />
        <xsd:element ref="properties" minOccurs="0" />
        <xsd:element ref="dt:datatypes"  minOccurs="0" />
        <xsd:element ref="fieldlist" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="indexlist" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="functionlist" minOccurs="0" maxOccurs="unbounded"  />
      </xsd:sequence>
      <xsd:attribute name="name"       type="xsd:string" use="required" />
      <xsd:attribute name="maintainer" type="xsd:string" />
      <xsd:attribute name="version"    type="xsd:string" />
      <xsd:attribute name="extends"    type="xsd:string" />
      <xsd:attribute name="defaultcontextintypedef"    type="xsd:string" />
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="status" />
  <xsd:element name="class">
    <xsd:complexType mixed="true">
      <xsd:sequence>
        <xsd:element ref="param" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute name="name" type="xsd:string" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="param">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute name="name" type="xsd:string" use="required" />
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="searchage" />

  <xsd:element name="names">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="singular" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="plural"   minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="singular">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute ref="xml:lang" />
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="plural">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute ref="xml:lang" />
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="descriptions">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="description" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="description">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute ref="xml:lang" />
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="properties">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="property" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="property">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute name="name" type="xsd:string" use="required" />
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>


  <xsd:element name="fieldlist">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="field" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
      <!-- you may want to xinclude fieldlists, xincludes may add xml:base attributes -->
      <xsd:attribute ref="xml:base" />
      <xsd:attribute name="id" type="xsd:ID"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="field">
    <xsd:complexType>
      <xsd:all>
        <xsd:element ref="descriptions" minOccurs="0" />
        <xsd:element ref="gui"          minOccurs="0" />
        <xsd:element ref="editor"       minOccurs="0" />
        <xsd:element ref="dt:datatype"     minOccurs="0" />
        <xsd:element ref="db"     minOccurs="0" />
      </xsd:all>
      <xsd:attribute name="name" type="xsd:string" />
      <xsd:attribute name="state">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="persistent" />
            <xsd:enumeration value="virtual" />
            <xsd:enumeration value="system" />
            <xsd:enumeration value="systemvirtual" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
      <xsd:attribute name="override">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="replace" />
            <xsd:enumeration value="merge" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
      <xsd:attribute name="readonly">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="true" />
            <xsd:enumeration value="false" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
      <!-- you may want to xinclude a field, xincludes may add xml:base attributes -->
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="gui">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="guiname" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="guiname">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute ref="xml:lang" />
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="editor">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="positions" minOccurs="0" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="positions">
    <xsd:complexType>
      <xsd:all>
        <xsd:element ref="input"  minOccurs="0" />
        <xsd:element ref="list"   minOccurs="0" />
        <xsd:element ref="search" minOccurs="0" />
      </xsd:all>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="input" />
  <xsd:element name="list" />
  <xsd:element name="search" />


  <xsd:element name="db">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="name" minOccurs="0" />
        <xsd:element ref="type" minOccurs="0" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="name" />

  <xsd:element name="type">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute name="state">
            <xsd:simpleType>
              <xsd:restriction base="xsd:string">
                <xsd:enumeration value="persistent" />
                <xsd:enumeration value="virtual" />
                <xsd:enumeration value="system" />
                <xsd:enumeration value="systemvirtual" />
              </xsd:restriction>
            </xsd:simpleType>
          </xsd:attribute>
          <xsd:attribute name="size" type="xsd:string" />
          <xsd:attribute name="notnull">
            <xsd:simpleType>
              <xsd:restriction base="xsd:string">
                <xsd:enumeration value="true" />
                <xsd:enumeration value="false" />
              </xsd:restriction>
            </xsd:simpleType>
          </xsd:attribute>
          <xsd:attribute name="unique">
            <xsd:simpleType>
              <xsd:restriction base="xsd:string">
                <xsd:enumeration value="true" />
                <xsd:enumeration value="false" />
                <xsd:enumeration value="implied" />
              </xsd:restriction>
            </xsd:simpleType>
          </xsd:attribute>
          <xsd:attribute name="required">
            <xsd:simpleType>
              <xsd:restriction base="xsd:string">
                <xsd:enumeration value="true" />
                <xsd:enumeration value="false" />
              </xsd:restriction>
            </xsd:simpleType>
          </xsd:attribute>
          <xsd:attribute name="readonly">
            <xsd:simpleType>
              <xsd:restriction base="xsd:string">
                <xsd:enumeration value="true" />
                <xsd:enumeration value="false" />
              </xsd:restriction>
            </xsd:simpleType>
          </xsd:attribute>
          <xsd:attribute name="key">
            <xsd:simpleType>
              <xsd:restriction base="xsd:string">
                <xsd:enumeration value="true" />
                <xsd:enumeration value="false" />
              </xsd:restriction>
            </xsd:simpleType>
          </xsd:attribute>
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="indexlist">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="index" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="index">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="indexfield" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute name="name" type="xsd:string" use="required" />
      <xsd:attribute name="override">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="replace" />
            <xsd:enumeration value="merge" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
      <xsd:attribute name="unique">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="true" />
            <xsd:enumeration value="false" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="indexfield">
    <xsd:complexType>
      <xsd:attribute name="name" type="xsd:string" use="required" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="functionlist">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="function" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="function">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="class" />
      </xsd:sequence>
      <xsd:attribute ref="xml:base" />
      <xsd:attribute name="name" type="xsd:string" />
      <xsd:attribute name="key" type="xsd:string" />
      <xsd:attribute name="override">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="replace" />
            <xsd:enumeration value="merge" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== mmbase/mmbase/contributions/CMSContainer/cmsc/utilities/config/applications/utilities/builders/properties.xml
<?xml version="1.0" encoding="UTF-8"?>
<builder
    xmlns="http://www.mmbase.org/xmlns/builder"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.mmbase.org/xmlns/builder 
                        http://www.mmbase.org/xmlns/builder.xsd"
	extends="object" maintainer="finalist.com" name="properties" version="1">
<!--
 
-->
   <status>active</status>
   <!--
   <class>Utilities.Properties</class>
   -->
   <searchage>70</searchage>
   <names>
      <singular xml:lang="nl">properties</singular>
      <singular xml:lang="en">properties</singular>
	  <singular xml:lang="zh">属性</singular>
      <plural xml:lang="nl">properties</plural>
      <plural xml:lang="en">properties</plural>
	  <plural xml:lang="zh">属性</plural>
   </names>
   <descriptions>
      <description xml:lang="nl"></description>
      <description xml:lang="en"></description>
	  <description xml:lang="zh"></description>
   </descriptions>

	<properties></properties>
   <fieldlist>
      <field>
         <descriptions>
            <description xml:lang="nl"></description>
            <description xml:lang="en"></description>
			<description xml:lang="zh"></description>
         </descriptions>
         <gui>
            <guiname xml:lang="nl">Naam</guiname>
			<guiname xml:lang="en">Key</guiname>
			<guiname xml:lang="zh">关键字</guiname>
         </gui>
         <editor>
            <positions>
					<input>4</input>
					<list>4</list>
					<search>4</search>
            </positions>
         </editor>
			<datatype base="line" xmlns="http://www.mmbase.org/xmlns/datatypes" />
         <db>
            <name>key</name>
            <type key="false" notnull="false" size="40" state="persistent">STRING</type>
         </db>
      </field>
      <field>
         <descriptions>
            <description xml:lang="nl"></description>
            <description xml:lang="en"></description>
			<description xml:lang="zh"></description>
         </descriptions>
         <gui>
            <guiname xml:lang="nl">Omschrijving</guiname>
            <guiname xml:lang="en">Description</guiname>
			<guiname xml:lang="zh">描述</guiname>
         </gui>
         <editor>
            <positions>
               <input>5</input>
               <list>-1</list>
               <search>-1</search>
            </positions>
         </editor>
			<datatype base="field" xmlns="http://www.mmbase.org/xmlns/datatypes" />
         <db>
            <name>description</name>
            <type key="false" notnull="false" size="1024" state="persistent">STRING</type>
         </db>
      </field>
      <field>
         <descriptions>
            <description xml:lang="nl"></description>
            <description xml:lang="en"></description>
			<description xml:lang="zh"></description>
         </descriptions>
         <gui>
            <guiname xml:lang="nl">Waarde</guiname>
			<guiname xml:lang="en">Value</guiname>
			<guiname xml:lang="zh">值</guiname>
         </gui>
         <editor>
            <positions>
               <input>6</input>
               <list>-1</list>
               <search>-1</search>
            </positions>
         </editor>
			<datatype base="field" xmlns="http://www.mmbase.org/xmlns/datatypes" />
         <db>
            <name>value</name>
            <type key="false" notnull="false" size="255" state="persistent">STRING</type>
         </db>
      </field>
      <field>
         <descriptions>
            <description xml:lang="nl"></description>
            <description xml:lang="en"></description>
			<description xml:lang="zh"></description>
         </descriptions>
         <gui>
            <guiname xml:lang="nl">Productie</guiname>
			<guiname xml:lang="en">Production</guiname>
			<guiname xml:lang="zh">生产</guiname>
         </gui>
         <editor>
            <positions>
               <input>7</input>
               <list>-1</list>
               <search>-1</search>
            </positions>
         </editor>
			<datatype base="field" xmlns="http://www.mmbase.org/xmlns/datatypes" />
         <db>
            <name>prod</name>
            <type key="false" notnull="false" size="255" state="persistent">STRING</type>
         </db>
      </field>
      <field>
         <descriptions>
            <description xml:lang="nl"></description>
            <description xml:lang="en"></description>
			<description xml:lang="zh"></description>
         </descriptions>
         <gui>
            <guiname xml:lang="nl">Acceptatie</guiname>
			<guiname xml:lang="en">Acceptance</guiname>
			<guiname xml:lang="zh">认可</guiname>
         </gui>
         <editor>
            <positions>
               <input>8</input>
               <list>-1</list>
               <search>-1</search>
            </positions>
         </editor>
			<datatype base="field" xmlns="http://www.mmbase.org/xmlns/datatypes" />
         <db>
            <name>preprod</name>
            <type key="false" notnull="false" size="255" state="persistent">STRING</type>
         </db>
      </field>
      <field>
         <descriptions>
            <description xml:lang="nl"></description>
            <description xml:lang="en"></description>
			<description xml:lang="zh"></description>
         </descriptions>
         <gui>
            <guiname xml:lang="nl">Test</guiname>
			<guiname xml:lang="en">Test</guiname>
			<guiname xml:lang="zh">测试</guiname>
         </gui>
         <editor>
            <positions>
               <input>9</input>
               <list>-1</list>
               <search>-1</search>
            </positions>
         </editor>
			<datatype base="field" xmlns="http://www.mmbase.org/xmlns/datatypes" />
         <db>
            <name>test</name>
            <type key="false" notnull="false" size="255" state="persistent">STRING</type>
         </db>
      </field>
      <field>
         <descriptions>
            <description xml:lang="nl"></description>
            <description xml:lang="en"></description>
			<description xml:lang="zh"></description>
         </descriptions>
         <gui>
            <guiname xml:lang="nl">Development</guiname>
			<guiname xml:lang="en">Development</guiname>
			<guiname xml:lang="zh">开发</guiname>
         </gui>
         <editor>
            <positions>
               <input>10</input>
               <list>-1</list>
               <search>-1</search>
            </positions>
         </editor>
			<datatype base="field" xmlns="http://www.mmbase.org/xmlns/datatypes" />
         <db>
            <name>dev</name>
            <type key="false" notnull="false" size="255" state="persistent">STRING</type>
         </db>
      </field>
      <field>
         <descriptions>
            <description xml:lang="nl"></description>
            <description xml:lang="en"></description>
			<description xml:lang="zh"></description>
         </descriptions>
         <gui>
            <guiname xml:lang="nl">Module</guiname>
			<guiname xml:lang="en">Module</guiname>
			<guiname xml:lang="zh">模型</guiname>
         </gui>
         <editor>
            <positions>
               <input>10</input>
               <list>-1</list>
               <search>-1</search>
            </positions>
         </editor>
			<datatype base="field" xmlns="http://www.mmbase.org/xmlns/datatypes" />
         <db>
            <name>module</name>
            <type key="false" notnull="false" size="255" state="persistent">STRING</type>
         </db>
      </field>
</fieldlist>
</builder>

=== mmbase/mmbase/contributions/CMSContainer_Modules/publish-remote/config/builders/Publisher/remotenodes.xml
<?xml version="1.0" encoding="UTF-8"?>
<builder extends="object" maintainer="mmbase.org" name="remotenodes" version="1"
    xmlns="http://www.mmbase.org/xmlns/builder"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mmbase.org/xmlns/builder http://www.mmbase.org/xmlns/builder.xsd">
    <searchage>14</searchage>
    <names>
        <singular xml:lang="us">RemoteNode</singular>
        <singular xml:lang="en">RemoteNode</singular>
        <singular xml:lang="nl">RemoteNode</singular>
        <plural xml:lang="us">RemoteNodes</plural>
        <plural xml:lang="en">RemoteNodes</plural>
        <plural xml:lang="nl">RemoteNodes</plural>
    </names>
    <descriptions>
        <description xml:lang="us">RemoteNodes are used to map remote mmbase nodes to this node</description>
        <description xml:lang="en">RemoteNodes are used to map remote mmbase nodes to this node</description>
        <description xml:lang="nl">RemoteNodes worden gebruikt om remote mmbase nodes te mappen naar lokale nodes</description>
    </descriptions>
    <fieldlist>
        <field name="timestamp" state="system">
            <gui>
                <guiname xml:lang="us">TimeStamp</guiname>
                <guiname xml:lang="en">TimeStamp</guiname>
                <guiname xml:lang="nl">TijdStempel</guiname>
            </gui>
            <editor>
                <positions>
                    <input>2</input>
                    <list>2</list>
                    <search>2</search>
                </positions>
            </editor>
            <datatype base="lastmodified" xmlns="http://www.mmbase.org/xmlns/datatypes"/>
        </field>
        <field name="sourcecloud">
            <gui>
                <guiname xml:lang="us">SourceCloud</guiname>
                <guiname xml:lang="en">SourceCloud</guiname>
                <guiname xml:lang="nl">SourceCloud</guiname>
            </gui>
            <editor>
                <positions>
                    <input>3</input>
                    <list>3</list>
                    <search>3</search>
                </positions>
            </editor>
            <datatype base="integer" xmlns="http://www.mmbase.org/xmlns/datatypes">
                <required value="true"/>
            </datatype>
        </field>
        <field name="sourcenumber">
            <gui>
                <guiname xml:lang="us">SourceNumber</guiname>
                <guiname xml:lang="en">SourceNumber</guiname>
                <guiname xml:lang="nl">SourceNummer</guiname>
            </gui>
            <editor>
                <positions>
                    <input>4</input>
                    <list>4</list>
                    <search>4</search>
                </positions>
            </editor>
            <datatype base="integer" xmlns="http://www.mmbase.org/xmlns/datatypes">
                <required value="true"/>
            </datatype>
        </field>
        <field name="destinationcloud">
            <gui>
                <guiname xml:lang="us">DestinationCloud</guiname>
                <guiname xml:lang="en">DestinationCloud</guiname>
                <guiname xml:lang="nl">DestinationCloud</guiname>
            </gui>
            <editor>
                <positions>
                    <input>5</input>
                    <list>5</list>
                    <search>5</search>
                </positions>
            </editor>
            <datatype base="integer" xmlns="http://www.mmbase.org/xmlns/datatypes">
                <required value="true"/>
            </datatype>
        </field>
        <field name="destinationnumber">
            <gui>
                <guiname xml:lang="us">DestinationNumber</guiname>
                <guiname xml:lang="en">DestinationNumber</guiname>
                <guiname xml:lang="nl">DestinationNumber</guiname>
            </gui>
            <editor>
                <positions>
                    <input>6</input>
                    <list>6</list>
                    <search>6</search>
                </positions>
            </editor>
            <datatype base="integer" xmlns="http://www.mmbase.org/xmlns/datatypes">
                <required value="true"/>
            </datatype>
        </field>
    </fieldlist>
    <indexlist>
        <index name="src">
            <indexfield name="sourcenumber"/>
            <indexfield name="sourcecloud"/>
        </index>
        <index name="dest">
            <indexfield name="destinationnumber"/>
            <indexfield name="destinationcloud"/>
        </index>
    </indexlist>
</builder>

=== mmbase/mmbase/contributions/poll/config/builders/poll/ip.xml
<?xml version="1.0" encoding="UTF-8"?>
<builder
    xmlns="http://www.mmbase.org/xmlns/builder"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.mmbase.org/xmlns/builder http://www.mmbase.org/xmlns/builder.xsd"
    name="ip" maintainer="mmbase.org" version="1" extends="object"> 
  <names>
    <singular xml:lang="en">IP</singular>
    <singular xml:lang="nl">IP</singular>
    <singular xml:lang="eo">IP</singular>
    <plural xml:lang="en">IPs</plural>
    <plural xml:lang="nl">IPs</plural>
    <plural xml:lang="eo">IP-oj</plural>
  </names>

  <fieldlist>
    <field name="IP">
      <editor>
        <positions>
          <list>1</list>
        </positions>
      </editor>
      <datatype base="eline" xmlns="http://www.mmbase.org/xmlns/datatypes">
        <maxLength value="255" />
      </datatype>
    </field>
    <field name="poll">
      <gui>
        <guiname xml:lang="en">Poll</guiname>
        <guiname xml:lang="nl">Poll</guiname>
        <guiname xml:lang="eo">Enketo</guiname>
      </gui>
      <editor>
        <positions>
          <list>2</list>
        </positions>
      </editor>
      <datatype base="node" xmlns="http://www.mmbase.org/xmlns/datatypes">
        <enumeration>
          <query type="poll" xmlns="http://www.mmbase.org/xmlns/searchquery" />
        </enumeration>
      </datatype>
    </field>
    <field name="answer">
      <gui>
        <guiname xml:lang="en">Answer</guiname>
        <guiname xml:lang="nl">Antwoord</guiname>
        <guiname xml:lang="eo">Respondo</guiname>
      </gui>
      <editor>
        <positions>
          <list>3</list>
        </positions>
      </editor>
      <datatype base="node" xmlns="http://www.mmbase.org/xmlns/datatypes">
        <enumeration>
          <query type="answer" xmlns="http://www.mmbase.org/xmlns/searchquery" />
        </enumeration>
      </datatype>
    </field>
    <field name="date">
      <gui>
        <guiname xml:lang="en">Date</guiname>
        <guiname xml:lang="nl">Datum</guiname>
        <guiname xml:lang="eo">Dato</guiname>
      </gui>
      <editor>
        <positions>
          <input>4</input>
          <list>4</list>
          <search>4</search>
        </positions>
      </editor>
      <datatype base="created" xmlns="http://www.mmbase.org/xmlns/datatypes" /> 
    </field>

  </fieldlist>
</builder>
